### PR TITLE
Implement CubismVector2

### PR DESCRIPTION
**Pull request by sr229**
This implements CubismVector2 API from CubismNative C++ API. Some behaviors may not work but I'm pretty sure C# is sane enough to be behaviorally similar to C++ in this case

This is one of the fixes for #77 as osuTK's Vector implementation is not behaviorally the same as Cubism's own vector implementation.

Signed-off-by: Ayane Satomi <chinodesuuu@gmail.com>

### CODE REVIEW

**Comment by sr229** [comment]
Confirmed working, not sure if this fixes #77 but it seems to actually be making the physics rig to move now.

https://user-images.githubusercontent.com/14976516/106278932-8a3f4f80-6276-11eb-8a1b-2663f017d797.mp4

**Comment by LeNitrous** [comment]
This is flipped. It always gives the smaller value.
https://github.com/vignette-project/vignette-application-live2d/blob/3d0f02024cfcf1de5e780dcc2660b7acfdb0b260/Vignette.Application.Live2D/Utils/CubismMath.cs#L13

**Comment by LeNitrous** [comment]
`NormalizationAngle` is missing but it should be fixed on my local repo.
https://github.com/vignette-project/vignette-application-live2d/blob/3d0f02024cfcf1de5e780dcc2660b7acfdb0b260/Vignette.Application.Live2D/Physics/CubismPhysics.cs#L49-L60

**Comment by LeNitrous** [comment]
These are also a typo. The 2nd argument should be maximum.
https://github.com/vignette-project/vignette-application-live2d/blob/3d0f02024cfcf1de5e780dcc2660b7acfdb0b260/Vignette.Application.Live2D/Physics/CubismPhysics.cs#L443-L445
https://github.com/vignette-project/vignette-application-live2d/blob/3d0f02024cfcf1de5e780dcc2660b7acfdb0b260/Vignette.Application.Live2D/Physics/CubismPhysics.cs#L465-L467

**Comment by LeNitrous** [comment]
I did apply these fixes on my end since it was zeroing out. In the end its still behaves exactly the same as if we used `osuTK.Vector2`. At this point I'm convinced that its likely precision errors.

**Comment by sr229** [comment]
> This is flipped. It always gives the smaller value.
> https://github.com/vignette-project/vignette-application-live2d/blob/3d0f02024cfcf1de5e780dcc2660b7acfdb0b260/Vignette.Application.Live2D/Utils/CubismMath.cs#L13

this is exactly how it was implemented in C++ but we can always replace this later on.

**Comment by sr229** [comment]
Closing since we're going to reimplement this to match unity's implementation instead.

**Pull request closed without merging**
